theme: jekyll-theme-minimal

plugins:
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-sitemap


# Google Analytics - https://desiredpersona.com/google-analytics-jekyll/
google_analytics: UA-29035632-1


#begin seo
title: Maker Faire Orlando
tagline: The Greatest Show (& Tell) on Earth!
description: Maker Faire Orlando is a community-organized, family-friendly celebration featuring local do-it-yourself science, art, rockets, robots, crafts, technology, music, hands-on-activities, and more. Itâ€™s an event where people show what they are making and share what they are learning. Maker Faire Orlando is produced by The Maker Effect Foundation.
logo: /assets/images/site-branding/mfo_two_line_border.png

defaults:
  -
    scope:
      path: ""
    values:
      image: /assets/images/site-branding/mfo_two_line_border.png
  -
    scope:
      path: "/assets/**/*.pdf"
    values:
      sitemap: false
  -
    scope:
      path: ""
      type: "exhibits" # a collection in your site, in plural form
    values:
      layout: "exhibit"
  -
    scope:
      path: "makers-json/index.html" #don't index the json
    values:
      sitemap: false
  -
    scope:
      path: "events-json/index.html" #don't index the json
    values:
      sitemap: false


collections:
  sponsors:
    output: false
    sort_by: sponsor-level
  exhibits:
    output: true
    sort_by: Name

# set timezone
timezone: America/New_York

newsletter_url: http://eepurl.com/bpCB8T

event_date_descr: November 13th & 14th, 2021

event_location_descr: Central Florida Fairgrounds & Expo Halls
cta_event_url: /attend

contact_email: makers@makerfaireorlando.com

event_year: 2021
event_name: Maker Faire Orlando
